import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Trophy, Swords, Shield, PlusCircle } from 'lucide-react';
import Bracket from './components/Bracket';
import RegisterModal from './components/RegisterModal';
import AdminModal from './components/AdminModal';

export default function App() {
  const [matches, setMatches] = useState([]);
  const [teams, setTeams] = useState([]);
  const [isRegisterOpen, setIsRegisterOpen] = useState(false);
  const [isAdminOpen, setIsAdminOpen] = useState(false);
  const [secretClicks, setSecretClicks] = useState(0);

  const fetchBracket = async () => {
    try {
      const res = await axios.get('/api/bracket');
      setMatches(res.data.matches);
      setTeams(res.data.teams);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchBracket();
  }, []);

  // Hidden Trigger: Ctrl + Shift + A
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.ctrlKey && e.shiftKey && e.key.toLowerCase() === 'a') {
        setIsAdminOpen(true);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  // Hidden Trigger: 5 clicks on Header Trophy
  const handleSecretClick = () => {
    setSecretClicks(prev => {
      if (prev + 1 >= 5) {
        setIsAdminOpen(true);
        return 0;
      }
      return prev + 1;
    });
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col">
      <header className="border-b border-slate-800 bg-slate-900/60 backdrop-blur-md sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3 cursor-pointer select-none" onClick={handleSecretClick}>
            <div className="p-2 bg-gradient-to-tr from-cyan-600 to-blue-600 rounded-xl shadow-lg shadow-cyan-500/20">
              <Trophy className="text-white w-6 h-6" />
            </div>
            <div>
              <h1 className="text-xl font-black uppercase tracking-wider bg-gradient-to-r from-white via-slate-200 to-slate-400 bg-clip-text text-transparent">
                IHS Tournament
              </h1>
              <p className="text-[10px] text-cyan-400 font-semibold tracking-widest uppercase">
                Double Elimination • MLBB Championship
              </p>
            </div>
          </div>

          <button
            onClick={() => setIsRegisterOpen(true)}
            className="flex items-center gap-2 bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs uppercase font-extrabold px-4 py-2 rounded-xl transition shadow-md shadow-cyan-500/20"
          >
            <PlusCircle size={16} /> Register Squad ({teams.length}/8)
          </button>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-8 flex-1 w-full">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
          <div className="bg-slate-900/60 border border-slate-800 p-4 rounded-xl flex items-center gap-3">
            <Shield className="text-cyan-400 w-8 h-8" />
            <div>
              <p className="text-xs text-slate-400">Registered Teams</p>
              <p className="text-lg font-bold text-white">{teams.length} / 8 Squads</p>
            </div>
          </div>
          <div className="bg-slate-900/60 border border-slate-800 p-4 rounded-xl flex items-center gap-3">
            <Swords className="text-yellow-400 w-8 h-8" />
            <div>
              <p className="text-xs text-slate-400">Match Format</p>
              <p className="text-lg font-bold text-white">Best of 3 (Bo3)</p>
            </div>
          </div>
          <div className="bg-slate-900/60 border border-slate-800 p-4 rounded-xl flex items-center gap-3">
            <Trophy className="text-red-400 w-8 h-8" />
            <div>
              <p className="text-xs text-slate-400">Lineup Rules</p>
              <p className="text-lg font-bold text-white">5 Starters + 1 Sub</p>
            </div>
          </div>
        </div>

        {matches.length === 0 ? (
          <div className="text-center py-20 bg-slate-900/30 border border-slate-800 rounded-2xl">
            <Swords className="w-12 h-12 text-slate-600 mx-auto mb-3" />
            <h3 className="text-lg font-bold text-slate-300">Bracket not generated yet</h3>
            <p className="text-sm text-slate-500 max-w-sm mx-auto mt-1">
              Teams are currently registering. The bracket will go live once generated by the tournament marshal.
            </p>
          </div>
        ) : (
          <Bracket matches={matches} />
        )}
      </main>

      <footer className="border-t border-slate-800/50 py-6 text-center text-xs text-slate-600">
        <p>© 2025 IHS Tournament. All rights reserved.</p>
        <span 
          onClick={() => setIsAdminOpen(true)} 
          className="inline-block w-2 h-2 rounded-full bg-slate-800 hover:bg-cyan-500 cursor-pointer mt-2" 
          title="Hidden Admin Console"
        />
      </footer>

      <RegisterModal isOpen={isRegisterOpen} onClose={() => setIsRegisterOpen(false)} onRegistered={fetchBracket} />
      <AdminModal isOpen={isAdminOpen} onClose={() => setIsAdminOpen(false)} matches={matches} onUpdate={fetchBracket} />
    </div>
  );
}